DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS TEST (
    a TEXT ,
    b TEXT ,
    c TEXT 
);

SELECT COUNT(*) FROM TEST;

INSERT INTO TEST (a,b,c) VALUES ('1', '2','3'); 
INSERT INTO TEST (a,b,c) VALUES ('1', '2','3'); 
INSERT INTO TEST (a,b,c) VALUES ('1', '2','3'); 

SELECT * FROM TEST;

ALTER TABLE TEST ADD d TEXT;
ALTER TABLE TEST ADD e TEXT DEFAULT 'FOCUS';

SELECT * FROM TEST;
