CREATE TABLE test (

   base INTEGER,
   notation TEXT
);

INSERT INTO TEST VALUES (1, 'ONCE COMP');
INSERT INTO TEST VALUES (2, 'TWOS COMP');
INSERT INTO TEST VALUES (3, 'THREES COMP');

SELECT * FROM test;

DROP TABLE TEST;

DROP TABLE IF EXISTS TEST;

SELECT * FROM test;

