DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS TEST (
    a INTEGER PRIMARY KEY ,
    b TEXT ,
    c TEXT 
);

SELECT COUNT(*) FROM TEST;

INSERT INTO TEST (b,c) VALUES ( '2','3'); 
INSERT INTO TEST (b,c) VALUES ( '2','3'); 
INSERT INTO TEST (b,c) VALUES ( '2','3'); 

SELECT * FROM TEST;

INSERT INTO TEST (a, b,c) VALUES (4, '2','3'); 


INSERT INTO TEST (a, b,c) VALUES (4, '2','3'); 

SELECT * FROM TEST;
