DELETE FROM CUSTOMER WHERE STATE = 'CM';
commit;

INSERT INTO CUSTOMER (NAME, ADDRESS) VALUES ('THISARA', 'KIRIBATHGODA');
INSERT INTO CUSTOMER (NAME) VALUES  ('KIRIBATHGODA');
	INSERT INTO CUSTOMER  VALUES (111, 'THISARA', 'KIRIBATHGODA', 'GAMAPAHA', 'WP', 10000);


	UPDATE CUSTOMER SET CITY = 'Metro' WHERE CITY='Hope';

	select * from customer;		