DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS TEST (
    a INT ,
    b INT 
);

INSERT INTO TEST VALUES (1,2);
INSERT INTO TEST VALUES (2,2);
INSERT INTO TEST VALUES (3,2);
INSERT INTO TEST VALUES (4,2);
INSERT INTO TEST VALUES (2,2);
INSERT INTO TEST VALUES (2,3);
INSERT INTO TEST VALUES (2,4);
INSERT INTO TEST VALUES (2,4);
INSERT INTO TEST VALUES (2,4);

SELECT * FROM TEST;
SELECT DISTINCT a FROM TEST;
SELECT DISTINCT B FROM TEST;
SELECT DISTINCT A,B FROM TEST;