DROP TABLE IF EXISTS DUPLICATE;

CREATE TABLE IF NOT EXISTS TEST (
    a INTEGER NOT NULL,
    b TEXT NOT NULL,
    c TEXT
);

SELECT COUNT(*) FROM TEST;

INSERT INTO TEST (a,b,c) VALUES (1, '2','3');

SELECT * FROM TEST;


INSERT INTO TEST (a,b,c) VALUES (1, '2', NULL);

SELECT * FROM TEST;

INSERT INTO TEST (a,b,c) VALUES (NULL, '2', NULL);

SELECT * FROM TEST;

DROP TABLE IF EXISTS TEST;